### PR TITLE
Make text selection highlight on iOS Safari

### PR DESCRIPTION
**Pull request by yiniw**

### CODE REVIEW

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by zenorocha** [comment]
Hey @gillrena,

Just tested on an iPad and iPhone but still not working.

**Comment by yiniw** [comment]
Oh no :(  btw, have you tried to use a button to enable text selection? Similar with what you did on Clipboard.js @zenorocha I've tested that way and at least it works with my iPhone with iOS 8.4.1

**Comment by zenorocha** [comment]
Confirmed that it works with user interaction.

**Comment by zenorocha** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/zenorocha/select/compare/e34884a~1...e34884a) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by zenorocha** [comment]
I've made a comment on #1, thanks @gillrena!

**Comment by yiniw** [comment]
No problem :) @zenorocha

**Pull request merged**
